# Generated by Django 4.2.6 on 2023-10-27 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0002_useraccount_member_gender_member_mob_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_no', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('age', models.CharField(blank=True, max_length=200, null=True)),
                ('user_height', models.CharField(blank=True, max_length=200, null=True)),
                ('user_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('target_weight', models.CharField(blank=True, max_length=200, null=True)),
                ('medical_condition', models.CharField(blank=True, choices=[('Diabetes', 'Diabetes'), ('Pre-Diabetes', 'Pre-Diabetes'), ('Cholesterol', 'Cholesterol'), ('Hypertension', 'Hypertension'), ('Thyroid', 'Thyroid')], max_length=200, null=True)),
                ('emotional_health', models.CharField(blank=True, choices=[('Excessive Stress', 'Excessive Stress'), ('Sleep Issues', 'Sleep Issues'), ('Anger Issues', 'Anger Issues'), ('Loneliness', 'Loneliness'), ('Relationship stress', 'Relationship stress')], max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('user_acc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutra.useraccount')),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
