# Generated by Django 4.2.6 on 2023-11-02 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutra', '0003_userdetails_trainer_expertise_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
