# Generated by Django 4.2.6 on 2023-11-04 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutra', '0004_alter_userdetails_user_acc_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Feet', 'Feet'), ('Forearms', 'Forearms'), ('Glutes', 'Glutes'), ('Head', 'Head'), ('Inseam', 'Inseam'), ('Jaw', 'Jaw'), ('Knee', 'Knee'), ('Legs', 'Legs'), ('Muscle', 'Muscle'), ('Neck', 'Neck'), ('Other', 'Other')], max_length=8)),
                ('e_name', models.CharField(choices=[], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=100)),
                ('user_query_message', models.TextField()),
                ('send_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
