# Generated by Django 4.2.6 on 2023-11-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0005_exerciescategory_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciescategory',
            name='e_name',
            field=models.CharField(max_length=100),
        ),
    ]
