# Generated by Django 4.2.6 on 2023-11-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0006_alter_exerciescategory_e_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciescategory',
            name='body_part',
            field=models.CharField(choices=[('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Feet', 'Feet'), ('Forearms', 'Forearms'), ('Glutes', 'Glutes'), ('Head', 'Head'), ('Inseam', 'Inseam'), ('Jaw', 'Jaw'), ('Knee', 'Knee'), ('Legs', 'Legs'), ('Muscle', 'Muscle'), ('Neck', 'Neck'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exerciescategory',
            name='e_name',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
