# Generated by Django 4.2.6 on 2023-11-04 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutra', '0007_alter_exerciescategory_body_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciescategory',
            name='e_name',
            field=models.CharField(choices=[('squat', 'squat'), ('deadlift', 'deadlift'), ('legpress', 'legpress'), ('dumbellfly', 'dumbellfly'), ('chestpress', 'chestpress'), ('overheadpress', 'overheadpress'), ('legcurl', 'legcurl'), ('abtwister', 'abtwister'), ('plank', 'plank'), ('biceps', 'biceps'), ('triceps', 'triceps'), ('crunches', 'crunches'), ('pushup', 'pushup'), ('pullups', 'pullups')], max_length=15),
        ),
        migrations.CreateModel(
            name='Excercies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.BooleanField(default=False)),
                ('e_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('e_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutra.exerciescategory')),
            ],
        ),
    ]
