# Generated by Django 4.2.6 on 2023-11-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0009_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='activity',
        ),
    ]
