# Generated by Django 4.2.6 on 2023-11-04 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0010_remove_schedule_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutra.excercies'),
        ),
    ]
