# Generated by Django 5.0.2 on 2024-04-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0013_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
    ]
