# Generated by Django 5.0.2 on 2024-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0014_remove_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mob_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
