# Generated by Django 5.0.2 on 2024-04-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutra', '0015_feedback_mob_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='mob_no',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='feedback',
            name='satisfy',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1234, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='uname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
